ENH: clasp support; GAS support
caporaso-lab/SurveySync pull request #30
Opened 2018-04-11 23:15 UTC by thermokarst

Fixes #8
Fixes #9 

---

Pair-programmed with @turan1393

2018-04-11 23:21 UTC, thermokarst commented
@turan1393, want to review this PR? See if you can pull down these changes and test it out locally. We can do that together on Friday if you wish, just let me know!

2018-04-13 18:18 UTC, turanoo approved these changes
This looks good to me! I was able to use it on my machine.

2018-04-13 18:59 UTC, turanoo requested changes
Please see the bug I found!

2018-04-13 18:59 UTC, turan1393 commented on README.md
> +cd dist && ./..node_modules/.bin/clasp push && cd ..
Found a typo in the deploy instructions.
`cd dist && ./..node_modules/.bin/clasp push && cd ..` is supposed to be `cd dist && ./../node_modules/.bin/clasp push && cd ..`

2018-04-13 19:25 UTC, merged