ENH: Makefile
caporaso-lab/SurveySync pull request #32
Opened 2018-04-18 20:41 UTC by turan1393

Fixes #2

2018-04-18 22:13 UTC, thermokarst requested changes
Thanks @turan1393 - I have a few changes requested inline. As well, some (or all) of the directives in this Makefile will need a `PHONY` config (see [here](https://github.com/qiime2/vm-playbooks/blob/master/Makefile#L6) for an example). You can read up on Makefiles a bit [here](https://www.gnu.org/software/make/manual/make.html). Thanks!

2018-04-18 22:13 UTC, thermokarst commented on Makefile
> +
Can you remove this extra blank line?

2018-04-18 22:13 UTC, thermokarst commented on Makefile
> +	./node_modules/.bin/clasp login
On second though, let's split these two commands into two separate directives `deploy` & `login`, does that make sense?

2018-04-18 22:13 UTC, thermokarst commented on Makefile
> +	install yarn
Should this be `yarn install`?

2018-04-20 00:06 UTC, turan1393 commented
@thermokarst,

Thank you for comments. I will make those changes and push the file again. Thank you.

2018-04-27 20:10 UTC, thermokarst requested changes
The `Makefile` looks great and works well! Can you please update the README to use the `make blah` directives where applicable?

2018-04-27 20:10 UTC, thermokarst commented on Makefile
> +	@echo "make dev    -------->> to install yarn package manager."
how about "to install dependencies using yarn."?

2018-04-27 20:15 UTC, turanoo commented on Makefile
> +	@echo "make dev    -------->> to install yarn package manager."
Yes, I will commit the new changes in a few. 💯

2018-04-27 21:09 UTC, thermokarst approved these changes

2018-04-27 21:09 UTC, merged