ENH: Download zip file from test server
caporaso-lab/SurveySync pull request #51
Opened 2018-05-29 23:58 UTC by turanoo

2018-05-30 00:46 UTC, thermokarst requested changes
Lookin' great @turanoo! A few minor requests, inline! 🎉

2018-05-30 00:46 UTC, thermokarst commented on src/config.js
> +// validate config function
`// validate config function` -> `// TODO validate config function as part of issue #43`

https://github.com/caporaso-lab/SurveySync/issues/43

2018-05-30 00:46 UTC, thermokarst commented on src/ui.js
> +  // TODO add config validation once we address issue-
`// TODO add config validation once we address issue-` -> `// TODO add config validation once we address issue #43`

https://github.com/caporaso-lab/SurveySync/issues/43

2018-05-30 00:46 UTC, thermokarst commented on src/data.js
> +  protectDB(insertDB(csvName));
If the database already exists, this will blow up:

![screen shot 2018-05-29 at 5 35 10 pm](https://user-images.githubusercontent.com/274668/40692429-a7dabc26-6366-11e8-9365-94651b2ce4fa.png)

Either, we should check for the existence of the DB (maybe in `insertDB`? That function could be renamed `upsertDB` and perform an [upsert operation](https://en.wiktionary.org/wiki/upsert)). Another option would be to delete the DB sheets after we have used that data to update the "main" sheet, but we don't have any of that code in place. What do you think?

2018-05-30 00:46 UTC, thermokarst commented on src/ui.js
> +  const blobs = unzipResponse(resp);
I am seeing the following error crop up when the code hits this point:

![screen shot 2018-05-29 at 5 37 58 pm](https://user-images.githubusercontent.com/274668/40692576-799fac6c-6367-11e8-9a78-44df944f445a.png)

The stackdriver log:

```
Incorrect range width, was 1 but should be 3 at writeDataToDB(addon.bundle:6814) at triggerDataUpdate(addon.bundle:6767)
```

I can help you look into this a bit more on Wednesday. This might just be related to the ZIP file I am serving - I used macOS to create it, and sometimes that util is poorly behaved.

2018-05-30 18:19 UTC, turanoo commented on src/data.js
> +  protectDB(insertDB(csvName));
I think I like the idea of the upsertDB function better. I think as of right now it makes more sense.

2018-05-30 23:34 UTC, thermokarst requested changes
Lookin' good @turanoo! A few minor comments inline.

2018-05-30 23:34 UTC, thermokarst commented on src/config.js
> +function validateConfig(config) {
Looks good. Could be converted to a `.map` and an [`.every`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every) - your call either way!

2018-05-30 23:34 UTC, thermokarst commented on src/testing.js
> +function deleteDatabaseSheets() {
I think we decided to prefix all of the functions in this module with the word "testing" to differentiate them in the global namespace. So, this would look like `testingDeleteDatabaseSheets`.

2018-05-30 23:34 UTC, thermokarst commented on src/testing.js
> +      case 'Sheet 1':
We probably don't want to hard-code this in here - maybe it makes more sense to invert the data here. We can save all of the DB sheet names in the propertiesservice store when we fetch data. Then, in this function we can look those sheets up from the props and remove them. Another option would be to see if the sheets API allows us to save arbitrary flags to sheet object --- you could mark these somehow as "temporary" sheets. Let me know what you think!

2018-05-30 23:34 UTC, thermokarst commented on src/ui.js
> +  SpreadsheetApp.getUi().alert('The Survey Configuration was left empty! Please reinitialize.');
How about we throw an `Error` here, instead? That way the UX and UI is consistent.

2018-05-30 23:34 UTC, thermokarst commented on src/ui.js
>      .addItem('Test Clearing Existing Configuration', 'testingClearExistingConfig')
Can you add a `.addSeparator()` between your testing funcs and the normal funcs? Just to visually partition them.

2018-05-30 23:34 UTC, thermokarst commented on src/data.js
> +  upsertDB(csvName);
since this function (`upsertDB`) returns a reference to the DB sheet, you can just assign `DB` here, eliminating the need for the next line!

2018-06-08 03:52 UTC, thermokarst approved these changes
LGTM, thanks @turanoo!!

2018-06-08 03:53 UTC, merged